### ISSUE TITLE
Question: Which libsass to download?

### ISSUE THREAD

**Issue by BrianaCamp** [guerillalabs/Sasspool#67]
Hey @jacobfentress,

Which language of libsass should be downloaded from http://sass-lang.com/libsass

Thanks!

**Comment by jacobfentress** [comment]
Hey @BrianaCamp. Don't install any version of libsass. It can be confusing.

I just updated the entire build process to use yarn instead of grunt (as we'll probably be using on other projects). The README has been updated. You now just need to have node and yarn installed to get everything working properly. Try it out and let me know if you have any trouble.
